### ISSUE TITLE
Seperation of EntityObjects & POCO

### ISSUE THREAD

**Issue by prindacerk** [raghav-rosberg/UnitOfWorkWithMultipleDBContext#1]
I am following your architecture style for my project which is great by the way. I am a beginner in this style of structure and I have been reading various articles about it. One thing I keep noticing is the main focus on separating dependencies between projects. Now in your solution, you have two projects (Entity, Data). However, the Data's DBContext is using the classes in Entity. Which makes the Entity Classes as EntityObjects. However, you then use them in service & presentation as POCO objects. This creates a dependency of the EntityObjects to the other tiers. 

So in future, if Database structure is changed but not needed for the presentation or service tiers, then this will not be useful.

In my understanding, the Entity project should have POCO classes and the Data should have the EntityObject classes. And in the repository, AutoMapper is used to map and convert the EntityObject class to POCO class to return to the caller.

Please feel free to correct me if my understanding is incorrect. Would really appreciate to learn the correct way this should be if my understanding is wrong.

**Comment by raghav-rosberg** [comment]
Hi,
Thanks for your observation. I have updated the framework which resolves the concerns you have mentioned.
I have completely removed the Automapper and updated with WebAPI 2 and custom token based authentication with refresh tokens.
So no presentation layer objects will be coupled with domain entities and no POCO classes are required.
You can try this solution and let me know if any more support is required.
